#
# Copyright (c) 2021-present, Trail of Bits, Inc.
# All rights reserved.
#
# This source code is licensed in accordance with the terms specified in
# the LICENSE file found in the root directory of this source tree.
#

name: Build

on:
  push:
    branches:
      - 'master'

    tags:
      - '*'

  pull_request:
    branches:
      - '*'

env:
  # Tells vcpkg where binary packages are stored.
  VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg/bincache
  # Setup compiler
  CC: clang-14
  CXX: clang++-14

jobs:
  build_linux:
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    steps:
      # setup circuitous
      - name: Clone the circuitous repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 1

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.2
        with:
          runCmd: |
            cmake --preset ninja-system-remill-x64-linux-rel \
            && cmake --build ./builds/ninja-system-remill-x64-linux-rel -j $(nproc) \
            && ctest --preset ninja-system-remill-x64-linux-rel-test --output-on-failure \
            && cpack -G TXZ --config ./builds/ninja-system-remill-x64-linux-rel/CPackConfig.cmake \
            || exit 1

  #    - name: Upload circuitous package artifact
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: circuitous-${{ matrix.image.name }}-${{ matrix.image.tag }}
  #       path: ${{ steps.paths.outputs.build }}/circuitous/package/
  #       retention-days: 30

  # pre-release:
  #     if: success() && github.ref == 'refs/heads/master'
  #     name: "Pre Release"
  #     runs-on: ubuntu-20.04
  #     needs: build_linux

  #     steps:
  #     - name: Clone the vast repository
  #       uses: actions/checkout@v3
  #       with:
  #         path: ./circuitous
  #         fetch-depth: 1

  #     - name: "Download build artifacts"
  #       id: download
  #       uses: actions/download-artifact@v3

  #     - name: "Publish Pre-Release"
  #       uses: "marvinpinto/action-automatic-releases@latest"
  #       with:
  #         repo_token: "${{ secrets.GITHUB_TOKEN }}"
  #         automatic_release_tag: "latest"
  #         prerelease: true
  #         title: "Development Build"
  #         files: |
  #           ./circuitous/LICENSE
  #           ${{steps.download.outputs.download-path}}/circuitous-*/*.tar.xz
