#
# Copyright (c) 2021-present, Trail of Bits, Inc.
# All rights reserved.
#
# This source code is licensed in accordance with the terms specified in
# the LICENSE file found in the root directory of this source tree.
#

name: Build

on:
  push:
    branches:
      - 'master'

    tags:
      - '*'

  pull_request:
    branches:
      - '*'

env:
  # Tells vcpkg where binary packages are stored.
  VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg/bincache
  # Setup compiler
  CC: clang-14
  CXX: clang++-14

jobs:
  build_linux:
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    steps:
      # setup circuitous
      - name: Clone the circuitous repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 1

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.2
        with:
          runCmd: |
            sudo cmake --preset ninja-system-remill-x64-linux-rel || exit 1
            sudo cmake --build ./builds/ninja-system-remill-x64-linux-rel -j $(nproc) || exit 1

            sudo ctest --preset ninja-system-remill-x64-linux-rel-test --output-on-failure || exit 1

            sudo cpack -G TXZ --config ./builds/ninja-system-remill-x64-linux-rel/CPackConfig.cmake || exit 1

      - name: Upload circuitous package artifact
        uses: actions/upload-artifact@v3
        with:
            name: circuitous-ubuntu-22.04
            path: /workspaces/circuitous/builds/ninja-system-remill-x64-linux-rel/package
            retention-days: 30
